version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
  kurento:
    image: kurento/kurento-media-server:6.16.0
    restart: unless-stopped
    ports:
      - 8888:8888

volumes:
  db: ~